### ISSUE TITLE
Running loginsight-export -h on windows without the HOME env variable causes error - need better handling

### ISSUE THREAD

**Issue by yogita23p** [vmware/loginsight-export#13]
C:\Users\yogitap\AppData\Local\Programs\Python\Python36-32\Scripts>loginsight-export -h
Traceback (most recent call last):
  File "c:\users\yogitap\appdata\local\programs\python\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\yogitap\appdata\local\programs\python\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\yogitap\AppData\Local\Programs\Python\Python36-32\Scripts\loginsight-export.exe\__main__.py", line 9, in <module>
  File "c:\users\yogitap\appdata\local\programs\python\python36-32\lib\site-packages\loginsightexport\__main__.py", line 188, in main
    parser, args = arguments()
  File "c:\users\yogitap\appdata\local\programs\python\python36-32\lib\site-packages\loginsightexport\__main__.py", line 68, in arguments
    default=os.path.join(os.environ['HOME'], ".netrc"),
  File "c:\users\yogitap\appdata\local\programs\python\python36-32\lib\os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'HOME'

HOMEPATH=\Users\UserName
USERPROFILE=C:\Users\UserName

**Comment by dsaojose** [comment]
Wrote a small fix here: https://github.com/vmware/loginsight-export/pull/14

**Comment by dsaojose** [comment]
Fix was merged.
