### ISSUE TITLE
Query with two Chart queries failed to export

### ISSUE THREAD

**Issue by yogita23p** [vmware/loginsight-export#15]
Count of events + Unique Count of hostname
appname starts with blah blah
text does not contain blah

2017-03-24 12:10:32,286 root INFO: Exporting /s/2edp95?
2017-03-24 12:10:32,294 loginsightexport.uidriver DEBUG: Reusing existing session cookie

2017-03-24 12:10:32,404 loginsightexport.paramhelper DEBUG: Cannot retrieve timeWindowToggle, returning {}
2017-03-24 12:10:32,408 loginsightexport.paramhelper DEBUG: Inserted blank query = ''
2017-03-24 12:10:32,410 loginsightexport.paramhelper DEBUG: Direct inserted startTimeMillis = 1489777051320
2017-03-24 12:10:32,416 loginsightexport.paramhelper DEBUG: Direct inserted endTimeMillis = 1490381851319
2017-03-24 12:10:32,417 loginsightexport.paramhelper DEBUG: Mapping list-of-dict item piqlFunctionGroups = [{'functions': [{'label': 'Count', 'value': 'COUNT', 'requiresField': False, 'numericOnly': False}], 'field': None}, {'functions': [{'label': 'Unique count', 'value': 'UCOUNT', 'requiresField': True, 'numericOnly': False}], 'field': {'internalName': 'hostname', 'displayName': 'hostname', 'displayNamespace': None}}]
Traceback (most recent call last):
  File "c:\users\yogitap\appdata\local\programs\python\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\yogitap\appdata\local\programs\python\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\yogitap\AppData\Local\Programs\Python\Python36-32\Scripts\loginsight-export.exe\__main__.py", line 9, in <module>
  File "c:\users\yogitap\appdata\local\programs\python\python36-32\lib\site-packages\loginsightexport\__main__.py", line 238, in main
    overview = retrieve_aggregate_results((root.start, root.end, 0), False)
  File "c:\users\yogitap\appdata\local\programs\python\python36-32\lib\site-packages\loginsightexport\paramhelper.py", line 264, in start
    return int(self.getExportChartHelper()['paramsHelper.startTimeMillis'])
  File "c:\users\yogitap\appdata\local\programs\python\python36-32\lib\site-packages\loginsightexport\paramhelper.py", line 226, in getExportChartHelper
    params['paramsHelper.%s[%d].piqlFunctions[%d]' % (insertedkey, counter, second_counter)] = innerlistitem['value']
TypeError: string indices must be integers

**Comment by alanjcastonguay** [comment]
Fixed
