### ISSUE TITLE
Count of events query with one filter failed

### ISSUE THREAD

**Issue by yogita23p** [vmware/loginsight-export#16]
Test\\output.1489989600000'] INFO: InconsistentFile 'C:\\Downloads_Yogi\\Export_LI_Test\\output.1489989600000': Incorrect quantity of events, found 1251
2017-03-24 15:18:12,396 loginsightexport.progress INFO: Aborted  42.9% = 6/14 files (0:00:00.438000 elapsed)
InconsistentFile 'C:\\Downloads_Yogi\\Export_LI_Test\\output.1489989600000': Incorrect quantity of events, found 1251 - Delete it and retry, or report a bug.

Deleted the file and retried but still got errors.

**Comment by yogita23p** [comment]
Second run gave these errors.
2017-03-24 15:25:28,182 loginsightexport.uidriver DEBUG: Retrieved results: <AggregateQuery: elapsed=0:01:00.626578, 0 bins containing 0 events>
Traceback (most recent call last):
  File "c:\users\yogitap\appdata\local\programs\python\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\yogitap\appdata\local\programs\python\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\yogitap\AppData\Local\Programs\Python\Python36-32\Scripts\loginsight-export.exe\__main__.py", line 9, in <module>
  File "c:\users\yogitap\appdata\local\programs\python\python36-32\lib\site-packages\loginsightexport\__main__.py", line 239, in main
    callback.start(overview)
  File "c:\users\yogitap\appdata\local\programs\python\python36-32\lib\site-packages\loginsightexport\progress.py", line 37, in start
    self._start = min([x[0] for x in bins])
ValueError: min() arg is an empty sequence

**Comment by austinb324** [comment]
@yogita23p I was getting those same errors. The only way I could resolve it was to downgrade my Python install to 3.4.0. The install instructions should probably be modified to "say 3.4.0" only instead of "3.4 or higher".
